# Generated by Django 6.0.6 on 2026-06-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='DH', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('photo', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('sports', 'Sports'), ('books', 'Books'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
